# -*- coding: utf-8 -*-
#
# Copyright (C) 2022 Storm Platform
#
# Storm Environment is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

version: "3.2"

services:
    nginx:
        image: nginx:1.21.3
        container_name: jupyterhub-nginx
        hostname: jupyterhub-nginx
        restart: unless-stopped
        volumes:
            - "./config/nginx/ssl:/certs:ro"
            - "./config/nginx/log:/var/log/nginx-fs"
            - "./config/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro"
            - "./config/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro"
        networks:
            - storm-net
        ports:
            - "443:443"
        env_file:
            - ./.env
        depends_on:
            - "jupyterhub"
